#!/bin/bash

# FreshMart Grocery App - Firebase Setup Script
# This script helps you set up Firebase for FreshMart

echo "🛍️  FreshMart Grocery App - Firebase Setup"
echo "=========================================="
echo ""
echo "Step 1: Get Firebase Credentials"
echo "  1. Go to: https://console.firebase.google.com/"
echo "  2. Click 'Add project'"
echo "  3. Enter name: freshmart-grocery"
echo "  4. Click 'Create project'"
echo ""
echo "Step 2: Enable Authentication"
echo "  1. In Firebase Console, click 'Authentication' (left menu)"
echo "  2. Click 'Get Started'"
echo "  3. Enable 'Email/Password' → Turn on"
echo "  4. Enable 'Google' → Turn on → Select your account"
echo "  5. Under 'Authorized domains' → Add 'localhost'"
echo ""
echo "Step 3: Create Firestore Database"
echo "  1. In Firebase Console, click 'Firestore Database' (left menu)"
echo "  2. Click 'Create database'"
echo "  3. Select 'Start in test mode'"
echo "  4. Choose region: 'asia-southeast1' (nearest to India)"
echo "  5. Click 'Enable'"
echo ""
echo "Step 4: Get Your Firebase Config"
echo "  1. In Firebase Console, click Settings (gear icon) → Project Settings"
echo "  2. Scroll to 'Your apps' section"
echo "  3. Click 'Firebase SDK snippet' → 'Config'"
echo "  4. Copy the config object"
echo ""
echo "Step 5: Update Firebase Config File"
echo "  1. Open: js/firebase-config.js"
echo "  2. Replace these values with your Firebase config:"
echo "     - YOUR_API_KEY"
echo "     - YOUR_PROJECT"
echo "     - YOUR_PROJECT_ID"
echo "     - YOUR_MESSAGING_SENDER_ID"
echo "     - YOUR_APP_ID"
echo ""
echo "Step 6: Update Firestore Security Rules"
echo "  1. In Firebase Console → Firestore Database → Rules"
echo "  2. Copy the rules from FIREBASE_SETUP.md"
echo "  3. Paste and click 'Publish'"
echo ""
echo "Step 7: Start Local Server"
echo "  Run one of these commands:"
echo "  - npm start"
echo "  - python -m http.server 8000"
echo "  - npx http-server"
echo ""
echo "Step 8: Test the App"
echo "  Open: http://localhost:8000/auth.html"
echo "  Click 'Sign up' and create a test account"
echo ""
echo "✅ Setup Complete!"
echo ""
echo "📚 For more help, see:"
echo "  - GETTING_STARTED.md"
echo "  - FIREBASE_SETUP.md"
echo "  - FIREBASE_QUICK_REFERENCE.md"
echo ""
echo "🚀 You're ready to build!"
